spring.application.name=ms-canal-whatsapp
spring.config.import=optional:configserver:http://localhost:8888

server.port=8085

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

twilio.account-sid=${TWILIO_ACCOUNT_SID}
twilio.auth-token=${TWILIO_AUTH_TOKEN}
twilio.whatsapp-number=${TWILIO_WHATSAPP_NUMBER}

management.endpoints.web.exposure.include=health,info