services:

  discovery-server:
    build:
      context: .
      dockerfile: discovery-server/Dockerfile
    container_name: discovery-server
    ports:
      - "8761:8761"
    networks:
      - consultorio-net

  config-server:
    build:
      context: .
      dockerfile: config-server/Dockerfile
    container_name: config-server
    ports:
      - "8888:8888"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
      EUREKA_INSTANCE_HOSTNAME: config-server
    depends_on:
      - discovery-server
    networks:
      - consultorio-net

  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
      EUREKA_INSTANCE_HOSTNAME: api-gateway
    depends_on:
      - discovery-server
      - config-server
    networks:
      - consultorio-net

  ms-citas:
    build:
      context: .
      dockerfile: ms-citas/Dockerfile
    container_name: ms-citas
    ports:
      - "8081:8081"
    environment:
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
      EUREKA_INSTANCE_HOSTNAME: ms-citas
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
    depends_on:
      - discovery-server
      - config-server
      - kafka
    networks:
      - consultorio-net

  ms-pacientes:
    build:
      context: .
      dockerfile: ms-pacientes/Dockerfile
    container_name: ms-pacientes
    ports:
      - "8082:8082"
    environment:
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
      EUREKA_INSTANCE_HOSTNAME: ms-pacientes
    depends_on:
      - discovery-server
      - config-server
    networks:
      - consultorio-net

  ms-medicos:
    build:
      context: .
      dockerfile: ms-medicos/Dockerfile
    container_name: ms-medicos
    ports:
      - "8083:8083"
    environment:
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
      EUREKA_INSTANCE_HOSTNAME: ms-medicos
    depends_on:
      - discovery-server
      - config-server
    networks:
      - consultorio-net

  ms-notificaciones:
    build:
      context: .
      dockerfile: ms-notificaciones/Dockerfile
    container_name: ms-notificaciones
    ports:
      - "8084:8084"
    environment:
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
      EUREKA_INSTANCE_HOSTNAME: ms-notificaciones
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
    depends_on:
      - discovery-server
      - config-server
      - kafka
    networks:
      - consultorio-net

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - consultorio-net

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - consultorio-net

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres_admin
      POSTGRES_PASSWORD: ${POSTGRES_ADMIN_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - consultorio-net

networks:
  consultorio-net:
    driver: bridge



volumes:
  postgres_data: