KafkaServer {
    org.apache.kafka.common.security.plain.PlainLoginModule required
    username="admin"
    password="admin-secret-dev"
    user_admin="admin-secret-dev"
    user_citas="citas-secret-dev"
    user_notificaciones="notificaciones-secret-dev";
};